spring:
  application:
    name: bibliotecaapi
  datasource:
    url: jdbc:postgresql://localhost:5433/biblioteca
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      # ddl-auto> update
      ddl-auto: none
    properties:
      hibernate.format_sql: true